### ISSUE TITLE
Can we adjust the global grid in `live-html` formats

### ISSUE THREAD

**Issue by zachcp** [r-wasm/quarto-live#101]
Hi,

Really nice work on quart live - it's a breeze to use.  Like  #55 and #59, I would like to use more screen real estate. In my case, even being able to override the CSS like you can with the `html` format would be great. For example this is a setting I use in other projects.  For HTML this would allow me to use columns to get side-by-side blocks if I use pyodide with OJS.

```yaml
// _quarto.yml
// can specify the global grid layout structure.

format:
  html:
    grid:
      sidebar-width: "150px"
      margin-width: "150px"
      body-width: "1200px"

```
