### ISSUE TITLE
webr packages tag breaks cell-options

### ISSUE THREAD

**Issue by arnaud-feldmann** [r-wasm/quarto-live#36]
Hi,

As suggested by @coatless I tried to switch from quarto-webr to quarto-live on [this branch](https://github.com/arnaud-feldmann/formation_r_drieets_prog_fonctionnelle/tree/quarto-live) in order to comply with an open-source license. However, I've reverted the changes for now. Seems like I can't fully disable the autorun mode.

I've added in _quarto.yml

```
webr:
  cell-options:
    autorun: false
    completion: true
```

However,
In some of my pages like [this one](https://github.com/arnaud-feldmann/formation_r_drieets_prog_fonctionnelle/blob/quarto-live/poo_s3.qmd) I use a webr `packages:` header. And those pages seems to break the "no autorun" I've tried to enforce (for any reason ;) )

Thanks for your work,

Arnaud

**Comment by georgestagg** [comment]
I think this might be a problem with how Quarto merges metadata, perhaps related to: https://github.com/quarto-dev/quarto-cli/issues/9864

While I investigate, does using the following YAML header work as a workaround? In `poo_s3.qmd`:

```yaml
---
title: "Programmation fonctionnelle objet en R (S3)"
format:
  live-html:
    webr:
      packages: ["dplyr", "disaggR"]
---
```
