### ISSUE TITLE
quarto-live in quarto books projects

### ISSUE THREAD

**Issue by higgi13425** [r-wasm/quarto-live#85]
At the moment, quarto-live does not appear to work in the setting of a quarto books project. A {webr} block will render as static text, without the ability to run or edit.

Is this a matter of changing the _quarto.yml?
or is this not able to work in this setting as yet.

**Comment by psychemedia** [comment]
Similarly with `{pyodide}` blocks.

**Comment by higgi13425** [comment]
The https://github.com/coatless/quarto-webr extension does work with quarto books, so now possible

**Comment by georgestagg** [comment]
It should be possible to use Quarto Live in books projects by specifying the `live-html` format in your `_quarto.yml` project file:

```yaml
project:
  type: book

book:
  title: "Quarto Book"
  chapters:
      - index.qmd

format: live-html
```
