### ISSUE TITLE
Incorrectly pulling dev rather than release version

### ISSUE THREAD

**Issue by psychemedia** [r-wasm/quarto-live#92]
In a Gihub action, I am using

```yaml
      - uses: quarto-dev/quarto-actions/setup@v2
        with:
          version: 1.6.40

      - name: Build quarto site
        run: |
          cd content
          quarto add r-wasm/quarto-live --no-prompt
          quarto render quarto_docs/ --no-execute --output-dir ../quarto_dist
          cp -r quarto_dist/ dist/quarto_output/
```

This pulls the dev version 0.1.3 of quarto live rather than the release 0.1.2:

```text
shell: /usr/bin/bash -e {0}
  env:
    pythonLocation: /opt/hostedtoolcache/Python/3.12.9/x64
    PKG_CONFIG_PATH: /opt/hostedtoolcache/Python/3.12.9/x64/lib/pkgconfig
    Python_ROOT_DIR: /opt/hostedtoolcache/Python/3.12.9/x64
    Python2_ROOT_DIR: /opt/hostedtoolcache/Python/3.12.9/x64
    Python3_ROOT_DIR: /opt/hostedtoolcache/Python/3.12.9/x64
    LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.12.9/x64/lib
    MAMBA_ROOT_PREFIX: /home/runner/micromamba
    MAMBA_EXE: /home/runner/micromamba-bin/micromamba
    CONDARC: /home/runner/work/_temp/setup-micromamba/.condarc
    BUNDLE_EXT: linux-amd64.deb
  
Downloading
[✓] Downloading

[✓] Unzipping
    Found 1 extension.
The following changes will be made:
Quarto Live   [Install]   0.1.3 (formats,filter)

[✓] Copying

[✓] Extension installation complete
Learn more about this extension at:
https://www.github.com/r-wasm/quarto-live#readme
ERROR: Unable to read the extension 'live'.
Please ensure that you provided the correct id and that the extension is installed.
Stack trace:
Please ensure that you provided the correct id and that the extension is installed.
    at loadExtension (file:///opt/quarto/bin/quarto.js:425[7](https://github.com/ouseful-demos/jupyterlite-tm112-demo/actions/runs/13633592147/job/38106776805#step:10:7)7:15)
    at Object.extension (file:///opt/quarto/bin/quarto.js:42475:34)
    at readExtensionFormat (file:///opt/quarto/bin/quarto.js:[8](https://github.com/ouseful-demos/jupyterlite-tm112-demo/actions/runs/13633592147/job/38106776805#step:10:8)0601:50)
    at resolveFormats (file:///opt/quarto/bin/quarto.js:8053[9](https://github.com/ouseful-demos/jupyterlite-tm112-demo/actions/runs/13633592147/job/38106776805#step:10:9):41)
    at eventLoopTick (ext:core/01_core.js:175:7)
    at async renderContexts (file:///opt/quarto/bin/quarto.js:80377:21)
    at async Object.renderFormats (file:///opt/quarto/bin/quarto.js:80421:22)
    at async readBaseInputIndex (file:///opt/quarto/bin/quarto.js:81724:21)
    at async inputTargetIndex (file:///opt/quarto/bin/quarto.js:817[12](https://github.com/ouseful-demos/jupyterlite-tm112-demo/actions/runs/13633592147/job/38106776805#step:10:12):19)
    at async resolveInputTarget (file:///opt/quarto/bin/quarto.js:81830:19)
Error: Process completed with exit code 1.
```
