### ISSUE TITLE
webr to html-live in a website project

### ISSUE THREAD

**Issue by klh281** [r-wasm/quarto-live#93]
Hello,

I have built a series of pages on my course website using the webr extension for Quarto. When using this extension, the rendered .html output respects the website’s theme.scss (which is stored in the root of the project). However, after switching to the quarto-live extension, the live-html format does not apply the theme.scss. Is there an additional YAML configuration required to ensure that the themes and formats defined for the entire website are applied?

Thank you for your assistance.

**Comment by georgestagg** [comment]
Hi,

I am unable to reproduce this. Do you have a minimal project I can take a look at where the `theme.scss` file does not apply?

For me this seems to work:

I have a Quarto project with `_quarto.yml`:

```yml
project:
  type: website

website:
  sidebar:
    contents:
      - href: index.qmd

theme:
  - cosmo
  - theme.scss
```

A `theme.scss` file:

```css
/*-- scss:defaults --*/
$h1-font-size: 5rem !default;

/*-- scss:rules --*/
h1, h2, h3, h4, h5, h6 {
  color: blue;
}
```

and a document `index.qmd`:

````md
---
title: Index
format: live-html
engine: knitr
---

{{< include _extensions/r-wasm/live/_knitr.qmd >}}

```{webr}
rnorm(100, 10, 10)
```

````

In this case, the heading settings in the `theme.scss` are applied:

![Image](https://github.com/user-attachments/assets/959188d3-c970-44d1-baab-25351bf7a377)
