### ISSUE TITLE
Live coding cells do not see to have access to resources under `project: resources`, only `pyodide: resources:`

### ISSUE THREAD

**Issue by joelostblom** [r-wasm/quarto-live#96]
[The documentation](https://r-wasm.github.io/quarto-live/reference/document-yaml.html#pyodide) about `pyodide: resources:` reads:

> Resources to be [loaded into the Pyodide VFS](https://r-wasm.github.io/quarto-live/other/resources.html). **Defaults to all resources.**

What does the last sentence refer to? I thought it mean that anything specified under `project: resources:` would automatically be detected by pyodide, but this seems to not be the case because in a project with the following YAML:

```yaml
project:
  type: website
  execute-dir: project
  resources:
    - data
```

The live coding cells, does not have access to the data directory. I have to add the following for them to access that directory:

```yaml
pyodide:
  resources:
    - data
```

I'm wondering if this is either a bug and live coding cells should have access to anything specified in `project: resources:` or I'm misinterpreting what the documentation is referring to.

**Comment by georgestagg** [comment]
This might be a bug with the yaml merging of `_quarto.yml` properties into the document properties. If you have just

```
  resources:
    - data
```

but directly in your `document.qmd` yaml header rather than the overall project `_quarto.yml`, does it work as expected?

**Comment by georgestagg** [comment]
Further to above:

In `_quarto.yml`, for me this works:

```yml
project:
  type: website

resources:
  - data
```

but this does not work:

```yml
project:
  type: website
  resources:
    - data
```

Perhaps things are related to https://github.com/quarto-dev/quarto-cli/issues/11139 somewhere along the line.

In any case, if the above also works for you it may be a reasonable fix for the moment.
