### ISSUE TITLE
output-dir option for live-revealjs

### ISSUE THREAD

**Issue by eijoac** [r-wasm/quarto-live#99]
When using the live-revealjs for slides , the `output-dir` option doesn't seem to work. Output are all rendered in the root project folder.

The `slides.qmd` file.
```
---
format:
  live-revealjs:
    theme: default
    output-dir: docs
title: "A Title"
---
```
Then, `quarto render slides.qmd` or `quarto preview slides.qmd`.

**Comment by georgestagg** [comment]
Hi,

This does not seem to work for me, even when using just the standard `revealjs:` format rather than `live-revealjs:`.

Here are two options that worked for me:

1) Create a new file in the root project folder, `_quarto.yml`, with contents:

```
project:
  output-dir: docs
```

Then render as normal.

OR 

2) Render the file giving the `output-dir` option on the command line:

```
quarto render slides.qmd --output-dir=docs
```

Would either of these work for you?

**Comment by eijoac** [comment]
If I just do the 2 you suggested, I got an error message "ERROR: The --output-dir flag can only be used when rendering projects."

On the other hand, I do have a project folder and a `_quarto.yml` file, but it's a website site project. I have an `index.qmd` file and that `slides.qmd` file in the same folder. What's interesting is that if the `-render` option isn't in the `_quarto.yml` file, `quarto render` works, i.e., both the website (`index.qmd`) and the slides (`slides.qmd`) renders correctly in the `docs` folder (the file level YAML configure in `slides.qmd` correctly overrides the project level configure in `_quarto.yml` when rendering the slides). However, if the `-render` option is there. `quarto render` doesn't output anything.

`quarto render` doesn't work.
```
project:
  type: website
  output-dir: docs
  render: 
    - "!deploy.md"

website:
  title: "Website Title"
 
theme:
  light: [cosmo, styles.scss]
  dark: solar
```

`quarto render` works.
```
project:
  type: website
  output-dir: docs

website:
  title: "Website Title"
 
theme:
  light: [cosmo, styles.scss]
  dark: solar
```
